services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  etl_setup:
    build: .
    depends_on:
      - postgres
    restart: "no"
    command: ["./wait-for-postgres.sh", "postgres", "/bin/bash", "run_etl.sh"]
    networks:
      - default

volumes:
  db:
    driver: local
